import Head from "next/head";
import "@/styles/globals.css";
import Layout from "@/components/layout";
import { LoginDataProvider } from "@/store/login-data";

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Hotel Brylant - system rezerwacji</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginDataProvider>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </LoginDataProvider>
    </>
  );
}
